# Do not modify this file!  It was generated by ‘nixos-generate-config’ # and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/47ccd9c0-22e4-430a-bd29-b60d085f5432";

  fileSystems."/home" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "subvol=@log" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "subvol=@containers" ];
    };

  fileSystems."/var/lib/containers" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "subvol=@containers" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "subvol=@vms" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E4DD-63F7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
