# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/312ce977-71a5-4001-b754-31dcaf55a675";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/312ce977-71a5-4001-b754-31dcaf55a675";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/312ce977-71a5-4001-b754-31dcaf55a675";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/312ce977-71a5-4001-b754-31dcaf55a675";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/312ce977-71a5-4001-b754-31dcaf55a675";
      fsType = "btrfs";
      options = [ "subvol=@cache" "compress=zstd" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/4490-9561";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
